### ISSUE TITLE
唉，猪猪侠弄的啊，至少说下吧

### ISSUE THREAD

**Issue by a4m** [rootphantomer/Blasting_dictionary#1]

**Comment by rootphantomer** [comment]
哪个？我的记得没把fuzz.wuyun.org的字典上传上去啊。其他都是我自己平常拿来备份的啊。

**Comment by a4m** [comment]
没看懂你说的啥

**Comment by rootphantomer** [comment]
我也没看见你说的啥？我以为你说我未经猪猪侠允许，把他的fuzz.wuyun.org的字典上传了，可我刚刚看了下，没有猪猪侠fuzz.wuyun.org的字典啊
